import { Injectable } from '@angular/core';
import { Skin } from '../models/skin.model';
export type { Skin };
import { Observable, of } from 'rxjs';
import { delay } from 'rxjs/operators';

@Injectable({
  providedIn: 'root'
})
export class SkinService {

  private skins: Skin[] = [
    {
        "name": "MAC-10 | Bronzer (Minimal Wear)",
        "description": "Exterior: Minimal Wear",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou7umeldfwPz3cy9N4sazq5CEgPPxIYTdn2xZ_It0juuWod723VDn-xZoYjj7JIHHcFQ5NF2Bq1m5lO67gpK4v8idyHRrpGB8skedCQAD",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Minimal Wear",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "UMP-45 | Green Swirl (Factory New)",
        "description": "Exterior: Factory New",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoo7e1f1JfwPzLeQJK-dmlnImNg8jwNqjQglRd4cJ5nqfE8Y7xiQG3rUo-MDz6JdCQdgNsNVnY-QXol-jtg5Hp6MjOwSY1s3N3-z-DyAlUGTKw",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Factory New",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "MAC-10 | Candy Apple (Minimal Wear)",
        "description": "Exterior: Minimal Wear",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou7umeldfwPz3YzhG09C_k4if2a6sNemJxT5Vu5Ym0r-RoI-hjgflrxJsNmGmIteVdFA9YVmGrFe6wubxxcjrqUztTV4",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Minimal Wear",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Sticker | FURIA (Gold) | Rio 2022",
        "description": "This item commemorates the IEM Rio 2022 CS:GO Championship.",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXQ9QVcJY8gulRPRUOCF7b_mMnGQVRLIgtbsvTwLwRm0fHNJWkS7t_mzdHTlaWma-uAkmhVv5YmibqQ9ImljQXtrRVrfSmtc6YktIOQ",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "N/A",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "★ Specialist Gloves | Lt. Commander (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DAQ1h3LAVbv6mxFABs3OXNYgJR_Nm1nYGHnuTgDKnYlWBC6dJOiejM-rP4jVC9vh5yNmz7d9WVcgA-aVzW_lC4ybi7g8W5uczNnXFj6XMjsH_ZnUSw1U4YbPsv26KwPeDdkA",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Charm | Diner Dog",
        "description": "This charm can be attached to any weapon you own. Each attached charm can be detached by using a Charm Detachment. Detached charms will be returned to your inventory.",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXI5BVcJos7pwgSQUXDVO2j0MPaXVY7Lgdou7O2OA5u1P_BfzZ9_927q5ODlufxferXxTxUuZMmi7uSo9qh2wTi-EtlMmD1J9SWewU4ZFjR8ge_w-bphcWi_MOekIoMHCo",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "N/A",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "FAMAS | Mecha Industries (Well-Worn)",
        "description": "Exterior: Well-Worn",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposLuoKhRf1OD3dzxP7c-JmYWIn_bLPr7Vn35cppUjjuuU8dSk3lDirUdrYGund9WWIFI-N1uE-VnoyO6918K_78uYynB9-n51IVd8Vjc",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Well-Worn",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "P250 | Sand Dune (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopujwezhz3MzbcDNG09GzkImemrmlYumGwW0H65Z337uQpNTw3wLi_RE_ZG-lLYWWI1VrMlDY-la2yL_om9bi609Wg2uD",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "StatTrak™ Five-SeveN | Violent Daimyo (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposLOzLhRlxfbGTj5X09q_goW0hPLiNrXukmpY5dx-teTE8YXghRrh_Udua2nyLYWTdAQ8YVrX-APryO7phcK66J3MzHA37HYitHvVnECzn1gSOXC2FBMV",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": true,
"float": "0.03213546468"
    },
    {
        "name": "UMP-45 | Arctic Wolf (Minimal Wear)",
        "description": "Exterior: Minimal Wear",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoo7e1f1Jf0Ob3ZDBSuImJg4iCg_LLNbrfkVRd4cJ5nqeU9tv02FK3rkppNmD7LYCReg84Yl_RqVO5xLzrjcS9vMnOzSFksiF2-z-DyLGNX1bO",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Minimal Wear",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "MAG-7 | Monster Call (Battle-Scarred)",
        "description": "Exterior: Battle-Scarred",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou7uifDhjxszFcDoV09G5mpOfkuXLMLrdmlRZ7cRnk6fDotuijgDnqhE6a2GgLI7AJwc2YwvU_VPtx-jp0cS9uZybyHtlsnNw-z-DyNIAlqz1",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Battle-Scarred",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Desert Eagle | Tilted (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposr-kLAtl7PDdTjJU6c6mlZOYqPblJrrukm5Q78l0teTE8YXghRq2qBVpYj36J4PGJFJtMlvQrFK-xr-5jZW-6c_AyXZl7CAgt32OnEfhn1gSOe8GIxAh",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "SCAR-20 | Assault (Well-Worn)",
        "description": "Exterior: Well-Worn",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopbmkOVUw7PDdTi5B7c6JlZOYluL4J4Tck29Y_cg_jOiSpNvx2AXi_UVoYT_2JoWccAM-MAzQ-1K3yObq1pa175rInCRjuj5iuyjB1bhLOg",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Well-Worn",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Dual Berettas | Royal Consorts (Minimal Wear)",
        "description": "Exterior: Minimal Wear",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpos7asPwJf1OD3dShD4OO0kZKOg-P1IITWmWdV7ctOnOzP_I_wt1i9rBsofWjxd9eVdFBoaAzQ-1jtxujn0ZbqvZvJwCdkuHUktn7clha1h00fZrZxxavJVZJGwZQ",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Minimal Wear",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Galil AR | Connexion (Battle-Scarred)",
        "description": "Exterior: Battle-Scarred",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposbupIgthwczPYgJF7dC_mL-bn_jxPbLJqWNU6dNoxOuX9Nms2lK380NsYWGmdobEe1RvZlDXqVe_wOi6h8W5u5yby3Q2syc8pSGK9z8aR-s",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Battle-Scarred",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Souvenir MP7 | Gunsmoke (Well-Worn)",
        "description": "Exterior: Well-Worn",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou6ryFA957PTNfS1H4uO7kYSCgvq6YO3UwT9Su8YoiLqQot2i2Q2yrxVrZjv1JoecJgJoN12EqVa9wea7gYj84sr5HLdanQ",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Well-Worn",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Five-SeveN | Boost Protocol (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposLOzLhRlxfbGTjpR09q_goW0hPLiNrXuk21E-8x-hNbM8Ij8nVn6_Bc_YWz1I46VJAZtMAmD_gS_lL29hJO_7ZjKmnQ36XMisHuIyR3l0AYMMLJINbhvCw",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "StatTrak™ Glock-18 | Block-18 (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposbaqKAxf1P_HcjZ97s6_l4u0mvj6N6nYl2Vu5cB1g_zMu46l2lHiqUtvZzugItOXJwVqZV7XqFDoxersg8W4vZzBwSFiuyZ2tivD30vgJZYzpQY",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": true,
"float": "0.03213546468"
    },
    {
        "name": "StatTrak™ M4A1-S | Flashback (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou-6kejhz2v_Nfz5H_uO1gb-Gw_alDL3dl3hZ6sRygdbM8Ij8nVn6_UQ6Mj_2cdCcJgM2ZQnT_QC3yOy7gJC_v8nMmHFiu3EksSqOnEO_1QYMMLKV5eK0QA",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": true,
"float": "0.03213546468"
    },
    {
        "name": "AWP | Redline (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot621FAR17PLfYQJB496klb-GkvP9Jrafxj0Iu5wh3r6V8I2i2QK3-0JlNW_0IYbAcQ5qN1-Dr1i-we27hJW_7oOJlyW4ZaUDog",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Desert Eagle | Code Red (Well-Worn)",
        "description": "Exterior: Well-Worn",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposr-kLAtl7PTbTjlH7du6kb-KkPDmNqjCmXlu5cB1g_zMu9un21XgrxBtamCnd9WWd1NoYlCGr1S2lOzm0cPq78zLznRnsilxsHjD30vghpPff7g",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Well-Worn",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "AK-47 | Inheritance (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot7HxfDhh2MzYfi9B6dC3nY60mvLwOq7c2G4G68cm07rCodz3iQS18hZpZjr6LYLAJw47ZFiGr1a5x7vv15S46pzXiSw09t9Tqzg",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "M4A4 | Desolate Space (Battle-Scarred)",
        "description": "Exterior: Battle-Scarred",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou-6kejhjxszFJTwW09izh4-HluPxDKjBl2hU1810i__Yu9SsjQC1_BI_Ym_ydYfDJA4-Nw3S_AW4x-271Ja8uMycznFluXRzsCvD30vgz57zwrA",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Battle-Scarred",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Zeus x27 | Swamp DDPAT (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpooru2LhVf2-r3dTRF5d-3mb-NmOXxIK_um25V4dB8xLmXp4j2jAziqkBqYjr0LNLGcAY5Ml3SqwfoyLu7jMLv6MzIn3ZjsnQ8pSGKepYPpaw",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "M4A4 | Etch Lord (Battle-Scarred)",
        "description": "Exterior: Battle-Scarred",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou-6kejhth_KcTi5M7dezlomfksj8NrrHjyUEuJcp3rmVrYitiwKyrUpqYGnyJISVcAY6ZV_QrFm5lO-9gJG7tJ-f1zI97fNWumAH",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Battle-Scarred",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "StatTrak™ Glock-18 | Moonrise (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposbaqKAxf0vL3djFN79eJxdi0guX2MrXum2Re5vp3j__E57P4jVC9vh5yZGHzJNSScwc7MFGBqFHoyOu60cS6vJ2cn3VnvHIn4S2OmES01E5PbPsv26LZKopslQ",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": true,
"float": "0.03213546468"
    },
    {
        "name": "SCAR-20 | Poultrygeist (Minimal Wear)",
        "description": "Exterior: Minimal Wear",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopbmkOVUw7ODYTi5B7c6Jl4iClPzxPb3YkWNF18l4jeHVu4j32APmqhZlMjqgJNLBegJvNVCB81O5lLy71pW0u5vOzXdgunUr7HvD30vgK7egzrs",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Minimal Wear",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "MAC-10 | Ensnared (Well-Worn)",
        "description": "Exterior: Well-Worn",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou7umeldf0Ob3fDxBvYyJhImTnvLLPr7Vn35cpscj37CS996g3FHj-EBpYWr6coPGcQFqZgqE8lPqle3pjJK5uJqbz3F9-n51qYN3NaA",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Well-Worn",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Sawed-Off | Black Sand (Battle-Scarred)",
        "description": "Exterior: Battle-Scarred",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopbuyLgNv1fX3cih9_92hkYSEkfHLMbfQlWBu-8R_jtbJ8I3jkRrmrkFpMmn2II-RdVU3ZFGEq1G-kru-1se96c7AmyAyuHIr4H3fyUDmn1gSOXTi9BT4",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Battle-Scarred",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "StatTrak™ MAC-10 | Light Box (Battle-Scarred)",
        "description": "Exterior: Battle-Scarred",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou7umeldf3vLLIG195dC6gZOCmPnLO77QgHIfvpF1i7uU99-h2lax80s4YGHxcoKVIA8_NQmD-FO8xObs1J-56pzAm2wj5He-Fl8F3A",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Battle-Scarred",
        "stattrak": true,
"float": "0.03213546468"
    },
    {
        "name": "Five-SeveN | Flame Test (Battle-Scarred)",
        "description": "Exterior: Battle-Scarred",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposLOzLhRlxfbGTjpR09q_goWYkuHxPYTZmX9u-sp1tf_I-oDwnGu8rhIqKneiJNSTIVVsYgqBq1O9xLjpjZO-uc_IwCZl6SkisXrbyUCy1R8ZbbM8m7XAHv9bMcIb",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Battle-Scarred",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Five-SeveN | Sky Blue (Minimal Wear)",
        "description": "Exterior: Minimal Wear",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposLOzLhRlxfbGTi5N6eO0mJWOqPb6N4TSnnle5cBOhuDG_Zi73w3k-0I_Mm71J9WQJlA-YQmB-gftwO3n1pG07ZvPwHZg6yYqtinVnAv330--FPI2kw",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Minimal Wear",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "MP9 | Buff Blue (Factory New)",
        "description": "Exterior: Factory New",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou6r8FA907PHEZDh96dixkZO0m_7zO6-fx2oCusQgju-XoNjw3ge3-kVoa2D7cIDEIAQ_MA7U-VPowuzqgJO-u4OJlyWWMBPqQA",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Factory New",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Glock-18 | Candy Apple (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposbaqKAxfwPz3YzhG09GzkImemrn3YO6DlTxVvsMo07GYptum2VCw-UNtZG73JY_HdFBtMFDU_1O9x-fum9bi6wiDRj41",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "AWP | Printstream (Well-Worn)",
        "description": "Exterior: Well-Worn",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot621FAZ3w8zYYzRM-M-ihoWKmsj5Nr_Yg2Yf6p0n2OzCpIql3gbt-kJlZGnzJ4XAIFM4ZQ7V8wK2yO68g5Pu7pvNzmwj5HeziYMobA",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Well-Worn",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Desert Eagle | Printstream (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposr-kLAtl7PDdTjlH7duJhJKCmePnJ6nUl2Zu5cB1g_zMu9mliwbm-hE6MjyiINORcAVsMFDV_li_yeq8h8TvuZ_IyCYx7HJ343vD30vgwZLZMlg",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "FAMAS | Crypsis (Well-Worn)",
        "description": "Exterior: Well-Worn",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposLuoKhRfwOP3dzxP7c-Jk4iEhOPLOrXCk2hF-_p8j-3I4IG72gTm_RZoamzzcYKRcwI9Z1vW-gC2wOvr0MDtvsufzSFkvyB05SnVyQv330-O_QM5Sw",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Well-Worn",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Tec-9 | Urban DDPAT (Minimal Wear)",
        "description": "Exterior: Minimal Wear",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoor-mcjhoyszMdS1D-OOjhoK0m_7zO6-fwjhVuZIgjL2R842g21e3qEBpNj_6IY-UI1JoNFqC-QDqxujuhZS16YOJlyVgu9XFkA",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Minimal Wear",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Sawed-Off | Snake Camo (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopbuyLgNv1fX3Yi19_9K3n4W0mvLwOq7c2GpTsJV0ju-Qo4mm0QfjqUpsYWyiII6RdQQ6N1CD_wO8lO_ugMS4vZ_XiSw0eFPwbnM",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "StatTrak™ Glock-18 | Wraiths (Factory New)",
        "description": "Exterior: Factory New",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposbaqKAxf1OD3djFN79fnzL-chfbgO6LCqWdY781lxLvDp4j2jQG280s_Yz2mLYbBeldraFvR-lntxurrjJbt7ZiaynJgu3U8pSGKuupEFa8",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Factory New",
        "stattrak": true,
"float": "0.03213546468"
    },
    {
        "name": "Music Kit | Tim Huling, Neo Noir",
        "description": "This Music Kit will replace all of the music in the game and is shareable with anyone you are playing with. It also includes an MVP Anthem that plays for everyone in the match when you are MVP.\n\nThe Music Kit replaces the following music:\n- Main Menu\n- Round Start and End\n- Map Objective\n- Ten Second Warning\n- Death Camera",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXO9B9WLbU5oA9OA1jZSuy428bdVGIkdEoC5-KkKlFih6XLdD4S6ITmzYXakq6sZ-uFx2gHvsN12rnHp9732ATh5QMyNMBtGfX6",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "N/A",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Tec-9 | Isaac (Minimal Wear)",
        "description": "Exterior: Minimal Wear",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoor-mcjhjxszcdD4b092lnYmGmOHLP7LWnn8fsMQm3rHA8N30igDlqEdrMm6mcYecelBsZQqCqFO9lLq-hpe8tJzMzmwj5HfUZ5uBQA",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Minimal Wear",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "P250 | Asiimov (Battle-Scarred)",
        "description": "Exterior: Battle-Scarred",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopujwezhjxszYI2gS092lnYmGmOHLO77QgHIf6pIpiO3F99ihjQC1_0FtMmr6JdKRd1RqZAyE_VG9wO3thMXvv8_MyGwj5HdnkkyTug",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Battle-Scarred",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "AK-47 | Elite Build (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot7HxfDhjxszJemkV09G3h5SOhe7LPr7Vn35cppwpju2Z9N6l3AKx_0E6Mjv3IYOSIQc5MlGE-VW_kLu5jMLovs7LyyN9-n51sJxz0nI",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "P250 | Franklin (Minimal Wear)",
        "description": "Exterior: Minimal Wear",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopujwezhjxszFfjNH9eO6nYeDg7mnZL-IkjMIu5cp3r-WptStiVG3qBFla27wLNXGIVM3N17YqADvxO7rm9bi6-wO2R-D",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Minimal Wear",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Dual Berettas | Hydro Strike (Battle-Scarred)",
        "description": "Exterior: Battle-Scarred",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpos7asPwJf1-bJfQJH4NWikb-DjvPmPITCgnlY48BOguzA45W7i1XjqhU4NTugI9XGclM2YVHQqVa5wLy-1sS-vp7AznphuHVx5XuInAv3309xIMGNWg",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Battle-Scarred",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "P90 | Wave Breaker (Battle-Scarred)",
        "description": "Exterior: Battle-Scarred",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopuP1FBc5g8zKfjJR-OO0mJWOqP_xMq3I2G5TucAh3euWrdSiilDh8ks4YzumJtORcAc3ZA2E_lXtwufn1Me9uJXXiSw0k_28XMo",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Battle-Scarred",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "MP7 | Cirrus (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou6ryFABz7PXBfzxO08y5m4yPkvbwJenum25V4dB8xLzH9Nym0QfnrkE5YDj2doCTdwBvM1jZqFDqkrvr1J69tc_BwCdh6HI8pSGKIxYjiKM",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "AWP | Chromatic Aberration (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot621FAR17PLfYQJB5M65mYG0h_76OITck29Y_cg_3ruZo9nziwXj-EBkN2zxdtSRJlRqZFHWqFe3yeu90ZC-v5mYzSFk7j5iuygAeEUWVQ",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "Five-SeveN | Orange Peel (Battle-Scarred)",
        "description": "Exterior: Battle-Scarred",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposLOzLhRlxfbGTi5S08i3hIW0mOX1PbzUqWNU6dNoxL2UpIig3QznrxY9MTv6JoPDJw82ZgqCqQK4xru6jMXtvZ7LmHcx6XY8pSGK4-RSEko",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Battle-Scarred",
        "stattrak": false,
"float": "0.03213546468"
    },
    {
        "name": "AK-47 | Redline (Field-Tested)",
        "description": "Exterior: Field-Tested",
        "price": 100,
        "imagem": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot7HxfDhjxszJemkV09-5lpKKqPrxN7LEmyVS7cYg3LuT94qm21GyqUpsa2j7IIDDJwI7YwvRrFi7lOa5hpfpvs_A1zI97fpmYHCU",
        "disponivel": true,
        "estoque": 1,
        "a_venda": false,
        "criado_em": "2025-06-24T03:45:20.968Z",
        "plataforma": "Steam",
        "condicao": "Field-Tested",
        "stattrak": false,
"float": "0.03213546468"
    }
];

  constructor() { }

  getSkins(): Observable<Skin[]> {
    // Simula uma chamada de API com 1.5 segundos de atraso
    return of(this.skins).pipe(delay(1500));
  }
}
